lang: en-US # e.g. uk, pl, en-US
bg_color: dark # can be dark, light or auto
# theme-color is main accent color and can be red, pink, fuchsia, purple, violet, indigo, blue, azure, cyan, jade, green,
# lime, yellow, amber, pumpkin, orange, sand, grey, zinc, slate. See samples on https://picocss.com/docs/version-picker
theme_color: azure
title: GitHub Pages Theme for Readme
description: Minimal theme to convert your README.md to the GitHub Pages site
remote_theme: devich/readme-landing-page